---
title: "Final Project"
author: "Benjamin Glossner"
date: "5/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
library(here)
library(lubridate)
library(readxl)
library(mapproj)
library(maps)
library(ggridges)
```

```{r}
map_theme <- (
  theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank())
)
```


```{r include=FALSE}
schools <- read_xlsx(here::here("FinalProject", "US_schools_data.xlsx"))
regionizer <- read_csv(here::here("FinalProject", "us census bureau regions and divisions.csv"))
```

```{r}
schools_cleaned <- schools %>%
  select(
    PRIMARY_KEY, TOTAL_EXPENDITURE, INSTRUCTION_EXPENDITURE,
    SUPPORT_SERVICES_EXPENDITURE, OTHER_EXPENDITURE, CAPITAL_OUTLAY_EXPENDITURE,
    ends_with("READING"), ends_with("MATHEMATICS")
  ) %>%
  mutate(
    Year = substr(PRIMARY_KEY, 1, 4),
    State = substring(PRIMARY_KEY, 6)
  )
```

```{r}
schools_cleaned <- schools_cleaned %>%
  pivot_longer(
    c(ends_with("READING"),  ends_with("MATHEMATICS")),
    names_to = c("Grade", "Race", "Sex", "Test"),
    names_sep = "_",
    values_to = "Test Score"
  )

regionizer <- regionizer %>%
  mutate(
    State = str_to_lower(State)
  )

schools_cleaned <- schools_cleaned %>%
  mutate(
    State = str_replace_all(str_to_lower(State), "_", " ")
  ) %>%
  left_join(regionizer, by = "State") %>%
  select(-PRIMARY_KEY)

schools_cleaned <- schools_cleaned %>%
  mutate(
    Grade = str_extract(Grade, "[0-9]$"),
    Sex = str_replace(Sex, "A", "all"),
    across(c("State", "Grade", "Race", "Sex", "Test", "Region", "Division"), as.factor)
  )
```

```{r}
temp_school <- schools_cleaned %>%
  select(INSTRUCTION_EXPENDITURE, `Test Score`, Region, State) %>%
  drop_na(INSTRUCTION_EXPENDITURE, `Test Score`)

# summary(temp_school)
# 
# states <- map_data("state")
# map.df <- merge(states,
#                 temp_school,
#                 by.x = "State",
#                 by.y = "Region",
#                 all.x=T)
# map.df <- map.df[order(map.df$order),]
# 
# map.df %>%
#   ggplot(mapping = aes(x=long,y=lat,group=group)) +
#   geom_polygon(aes(fill=REGION)) +
#   geom_path() +
#   coord_map() +
#   labs(title = "Labeled Regions in the Continental US") +
#   map_theme

schools_cleaned_f %>%
  drop_na(INSTRUCTION_EXPENDITURE, `Test Score`) %>%
  ggplot(mapping = aes(x = INSTRUCTION_EXPENDITURE, y = `Test Score`)) +
  geom_smooth() +
  facet_wrap(~ Region, ncol = 1)
```

```{r}
schools_cleaned_f %>%
  drop_na(`Test Score`) %>%
  ggplot(mapping = aes(x = `Test Score`)) +
  geom_ri
```



