---
title: "Final Project"
author: "Christopher Price"
date: "5/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(readxl)
```

```{r}
schools <- read_xlsx(here::here("US_schools_data.xlsx"))
regionizer <- read_csv(here::here("us census bureau regions and divisions.csv"))
```

```{r}
schools %>%
  
```

# Data Cleaning
```{r}
schools_cleaned <- schools %>%
  select(
    PRIMARY_KEY, TOTAL_EXPENDITURE, INSTRUCTION_EXPENDITURE, 
    SUPPORT_SERVICES_EXPENDITURE, OTHER_EXPENDITURE, CAPITAL_OUTLAY_EXPENDITURE,
    ends_with("READING"), ends_with("MATHEMATICS")
  ) %>%
  mutate(
    Year = substr(PRIMARY_KEY, 1, 4),
    State = substring(PRIMARY_KEY, 6)
  )
```

```{r}
schools_cleaned <- schools_cleaned %>%
  pivot_longer(
    c(ends_with("READING"), ends_with("MATHEMATICS")),
    names_to = c("grade", "race", "sex", "test"),
    names_sep = "_",
    values_to = "Test Score"
  )

regionizer <- regionizer %>%
  mutate(
    State = str_to_lower(State)
  )

schools_cleaned <- schools_cleaned %>%
  mutate(
    State = str_replace_all(str_to_lower(State), "_", " ")
  ) %>%
  left_join(regionizer, by = "State") %>%
  select(-PRIMARY_KEY)

schools_cleaned %>%
  mutate(
    grade = as.factor(str_extract(grade, "[0-9]$")),
    sex = str_replace(sex, "A","all"),
    across(c("State", "grade", "race", "sex", "test", "Region", "Division"),
           as.factor)
  )
```







